#!/usr/bin/env node
/**
 * Vivah Planner — Git Pre-Commit Hook Installer
 * Sets up .git/hooks/pre-commit to automatically run `node scripts/update-docs.cjs`
 * and stage updated documentation before every commit.
 */

const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.resolve(__dirname, '..');
const HOOKS_DIR = path.join(ROOT_DIR, '.git', 'hooks');
const PRE_COMMIT_HOOK = path.join(HOOKS_DIR, 'pre-commit');

const HOOK_SCRIPT_CONTENT = `#!/bin/sh
# Vivah Planner — Pre-commit hook to update module documentation
# Automatically generated by scripts/install-hooks.cjs

echo "🔄 Running automated docs update hook for modules and sections..."
node scripts/update-docs.cjs

if [ $? -ne 0 ]; then
  echo "❌ Documentation update script failed! Aborting commit."
  exit 1
fi

# Automatically stage any updated documentation files
if [ -d "docs" ]; then
  git add docs/
fi

echo "✅ Documentation verified and staged."
exit 0
`;

function installHook() {
  if (!fs.existsSync(HOOKS_DIR)) {
    console.error('❌ .git/hooks directory not found. Are you in the root of a git repository?');
    process.exit(1);
  }

  fs.writeFileSync(PRE_COMMIT_HOOK, HOOK_SCRIPT_CONTENT, { mode: 0o755 });
  console.log(`✅ Pre-commit hook successfully installed at: ${path.relative(ROOT_DIR, PRE_COMMIT_HOOK)}`);
}

installHook();
